# Generated by Django 2.2.2 on 2019-06-23 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentsAll',
            new_name='Student',
        ),
    ]
