# Generated by Django 2.2.2 on 2019-06-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0002_auto_20190623_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsiscame',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='studentsiscame',
            name='name',
        ),
        migrations.AddField(
            model_name='lecture',
            name='student',
            field=models.ManyToManyField(to='lecturer.Student'),
        ),
    ]
