# Generated by Django 2.2.2 on 2019-06-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0003_auto_20190624_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='name',
            field=models.CharField(default='default lecture', max_length=200),
        ),
    ]
