# Generated by Django 2.2.2 on 2019-06-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0004_lecture_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='student',
            field=models.ManyToManyField(blank=True, to='lecturer.Student'),
        ),
    ]
