# Generated by Django 2.2.2 on 2019-06-28 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0005_auto_20190624_1549'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentsIsCame',
        ),
    ]
